export const DARK_THEME = {
  pageBg: 'bg-zinc-950',
  cardBg: 'bg-zinc-900',
  innerBg: 'bg-zinc-950',
  cardBorder: 'border-zinc-800',
  innerBorder: 'border-zinc-800',
  labelText: 'text-zinc-500',
  headingText: 'text-zinc-100',
  bodyText: 'text-zinc-300',
  mutedText: 'text-zinc-600',
  placeholderCls: 'placeholder-zinc-700',
  accent: 'text-yellow-300',
  accentBg: 'bg-yellow-300',
  accentBorder: 'border-yellow-300',
  accentHover: 'hover:border-yellow-300 hover:text-yellow-300 hover:bg-yellow-300/5',
  accentGlow: 'bg-yellow-300/10 border-yellow-300/30',
  accentComplete: 'text-yellow-300',
  progressTrack: 'bg-zinc-800',
  progressFill: 'bg-yellow-300',
  heatmapEmpty: { backgroundColor: '#0b0b0b', borderColor: '#27272a', color: '#a1a1aa' },
  typedCorrect: 'text-yellow-300',
  cursor: 'border-yellow-300',
  toggleBg: 'bg-zinc-800 hover:bg-zinc-700',
  toggleIcon: '☀️',
  toggleLabel: 'Light',
}

export const LIGHT_THEME = {
  pageBg: 'bg-slate-100',
  cardBg: 'bg-white',
  innerBg: 'bg-slate-50',
  cardBorder: 'border-slate-200',
  innerBorder: 'border-slate-200',
  labelText: 'text-slate-400',
  headingText: 'text-slate-800',
  bodyText: 'text-slate-700',
  mutedText: 'text-slate-400',
  placeholderCls: 'placeholder-slate-300',
  accent: 'text-indigo-600',
  accentBg: 'bg-indigo-600',
  accentBorder: 'border-indigo-500',
  accentHover: 'hover:border-indigo-500 hover:text-indigo-600 hover:bg-indigo-50',
  accentGlow: 'bg-indigo-50 border-indigo-200',
  accentComplete: 'text-indigo-600',
  progressTrack: 'bg-slate-200',
  progressFill: 'bg-indigo-500',
  heatmapEmpty: { backgroundColor: '#f1f5f9', borderColor: '#cbd5e1', color: '#64748b' },
  typedCorrect: 'text-indigo-500',
  cursor: 'border-indigo-500',
  toggleBg: 'bg-slate-200 hover:bg-slate-300',
  toggleIcon: '🌙',
  toggleLabel: 'Dark',
}
